title: my. hyde
author: GitHub User
email: djradon@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a beastly, brutish site
theme: minima

# social links
twitter_username: dvrchrdsn # DO NOT include the @ character, or else the build will fail!
github_username:  djradon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
